In [9]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [10]:
!cat toy.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [11]:
import pandas as pd

In [12]:
import numpy as np

In [13]:
f = pd.read_csv('toy.txt')

In [14]:
f

45   Federal-gov
0  33       Private
1  19       Private
2  47       Private
3  30     Local-gov
4  37       Private
5  35       Private
6  33       Private
7  40       Private
8  54   Federal-gov

In [15]:
pd.get_dummies(f)

45   Federal-gov_ Federal-gov   Federal-gov_ Local-gov  \
0  33                          0                        0   
1  19                          0                        0   
2  47                          0                        0   
3  30                          0                        1   
4  37                          0                        0   
5  35                          0                        0   
6  33                          0                        0   
7  40                          0                        0   
8  54                          1                        0   

    Federal-gov_ Private  
0                      1  
1                      1  
2                      1  
3                      0  
4                      1  
5                      1  
6                      1  
7                      1  
8                      0

In [16]:
f['age']

KeyError: 'age'

In [17]:
names = ['age', 'sector']

In [18]:
f = pd.read_csv('toy.txt', names=names)

In [19]:
f

age        sector
0   45   Federal-gov
1   33       Private
2   19       Private
3   47       Private
4   30     Local-gov
5   37       Private
6   35       Private
7   33       Private
8   40       Private
9   54   Federal-gov

In [20]:
f['age']

0    45
1    33
2    19
3    47
4    30
5    37
6    35
7    33
8    40
9    54
Name: age, dtype: int64

In [21]:
f['sector']

0     Federal-gov
1         Private
2         Private
3         Private
4       Local-gov
5         Private
6         Private
7         Private
8         Private
9     Federal-gov
Name: sector, dtype: object

In [22]:
type(f['age'])

pandas.core.series.Series

In [23]:
f[0]

KeyError: 0

In [24]:
f.head()

age        sector
0   45   Federal-gov
1   33       Private
2   19       Private
3   47       Private
4   30     Local-gov

In [25]:
f.tail()

age        sector
5   37       Private
6   35       Private
7   33       Private
8   40       Private
9   54   Federal-gov

In [26]:
pd.get_dummies(f)

age  sector_ Federal-gov  sector_ Local-gov  sector_ Private
0   45                    1                  0                0
1   33                    0                  0                1
2   19                    0                  0                1
3   47                    0                  0                1
4   30                    0                  1                0
5   37                    0                  0                1
6   35                    0                  0                1
7   33                    0                  0                1
8   40                    0                  0                1
9   54                    1                  0                0

In [27]:
pd.get_dummies(f['age'])

19  30  33  35  37  40  45  47  54
0   0   0   0   0   0   0   1   0   0
1   0   0   1   0   0   0   0   0   0
2   1   0   0   0   0   0   0   0   0
3   0   0   0   0   0   0   0   1   0
4   0   1   0   0   0   0   0   0   0
5   0   0   0   0   1   0   0   0   0
6   0   0   0   1   0   0   0   0   0
7   0   0   1   0   0   0   0   0   0
8   0   0   0   0   0   1   0   0   0
9   0   0   0   0   0   0   0   0   1

In [28]:
type(pd.get_dummies(f['age']))

pandas.core.frame.DataFrame

In [29]:
np.array(pd.get_dummies(f['age']))

array([[0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [30]:
np.array(pd.get_dummies(f['age']), dtype=int)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [31]:
np.array(pd.get_dummies(f['sector']), dtype=int)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0]])

In [32]:
f['sector']

0     Federal-gov
1         Private
2         Private
3         Private
4       Local-gov
5         Private
6         Private
7         Private
8         Private
9     Federal-gov
Name: sector, dtype: object

In [33]:
age = np.array(pd.get_dummies(f['age']), dtype=int)

In [34]:
sector = np.array(pd.get_dummies(f['sector']), dtype=int)

In [35]:
np.concatenate((age, sector))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 9 and the array at index 1 has size 3

In [36]:
np.concatenate((age, sector), axis=1)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]])

In [37]:
open('toy.txt').readlines()

['45, Federal-gov\n',
 '33, Private\n',
 '19, Private\n',
 '47, Private\n',
 '30, Local-gov\n',
 '37, Private\n',
 '35, Private\n',
 '33, Private\n',
 '40, Private\n',
 '54, Federal-gov\n']

In [38]:
len(open('toy.txt').readlines())

10

In [39]:
[s.split(", ") for s in open('toy.txt').readlines()]

[['45', 'Federal-gov\n'],
 ['33', 'Private\n'],
 ['19', 'Private\n'],
 ['47', 'Private\n'],
 ['30', 'Local-gov\n'],
 ['37', 'Private\n'],
 ['35', 'Private\n'],
 ['33', 'Private\n'],
 ['40', 'Private\n'],
 ['54', 'Federal-gov\n']]

In [40]:
[s.strip().split(", ") for s in open('toy.txt').readlines()]

[['45', 'Federal-gov'],
 ['33', 'Private'],
 ['19', 'Private'],
 ['47', 'Private'],
 ['30', 'Local-gov'],
 ['37', 'Private'],
 ['35', 'Private'],
 ['33', 'Private'],
 ['40', 'Private'],
 ['54', 'Federal-gov']]

In [52]:
data = [s.strip().split(", ") for s in open('toy.txt').readlines()]


In [53]:
data

[['45', 'Federal-gov'],
 ['33', 'Private'],
 ['19', 'Private'],
 ['47', 'Private'],
 ['30', 'Local-gov'],
 ['37', 'Private'],
 ['35', 'Private'],
 ['33', 'Private'],
 ['40', 'Private'],
 ['54', 'Federal-gov']]

In [54]:
mapping = {}

In [55]:
new_data = []

In [56]:
print('ran')
for row in data:
    new_row = []
    for j, x in enumerate(row):
        print(row)
        feature = (j, x)
        if feature not in mapping:
            mapping[feature] = len(mapping) # insert a new feature into the index
        new_row.append(mapping[feature])
    new_data.append(new_row)

ran
['45', 'Federal-gov']
['45', 'Federal-gov']
['33', 'Private']
['33', 'Private']
['19', 'Private']
['19', 'Private']
['47', 'Private']
['47', 'Private']
['30', 'Local-gov']
['30', 'Local-gov']
['37', 'Private']
['37', 'Private']
['35', 'Private']
['35', 'Private']
['33', 'Private']
['33', 'Private']
['40', 'Private']
['40', 'Private']
['54', 'Federal-gov']
['54', 'Federal-gov']


In [57]:
new_data

[[0, 1],
 [2, 3],
 [4, 3],
 [5, 3],
 [6, 7],
 [8, 3],
 [9, 3],
 [2, 3],
 [10, 3],
 [11, 1]]

In [58]:
mapping

{(0, '45'): 0,
 (1, 'Federal-gov'): 1,
 (0, '33'): 2,
 (1, 'Private'): 3,
 (0, '19'): 4,
 (0, '47'): 5,
 (0, '30'): 6,
 (1, 'Local-gov'): 7,
 (0, '37'): 8,
 (0, '35'): 9,
 (0, '40'): 10,
 (0, '54'): 11}

In [41]:
len(mapping)

12

In [61]:
bindata = np.zeros((10, 12))

In [43]:
bindata

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [59]:
for i, row in new_data:
    for x in row:
        bindata[i][x] = 1

TypeError: 'int' object is not iterable

In [45]:
for i, row in enumerate(new_data):
    print i, row


0 [0, 1]
1 [2, 3]
2 [4, 3]
3 [5, 3]
4 [6, 7]
5 [8, 3]
6 [9, 3]
7 [2, 3]
8 [10, 3]
9 [11, 1]


In [62]:
for i, row in enumerate(new_data):
    for x in row:
        bindata[i][x] = 1

In [63]:
bindata

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
np.concatenate((np.array(pd.get_dummies(f['age'])), np.array(pd.get_dummies(f['sector']))), axis=1)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]], dtype=uint8)

In [49]:
f

age        sector
0   45   Federal-gov
1   33       Private
2   19       Private
3   47       Private
4   30     Local-gov
5   37       Private
6   35       Private
7   33       Private
8   40       Private
9   54   Federal-gov