In [1]:
import numpy as np
import pandas as pd
import pprint
from collections import defaultdict, Counter


In [2]:
# Read CSV text file
dev = [s.strip().split(", ") for s in open('hw1-data/income.dev.txt').readlines()]

train = [s.strip().split(", ") for s in open('hw1-data/income.train.txt').readlines()]

In [3]:
dev

[['45',
  'Federal-gov',
  'Bachelors',
  'Married-civ-spouse',
  'Adm-clerical',
  'White',
  'Male',
  '45',
  'United-States',
  '<=50K'],
 ['33',
  'Private',
  '5th-6th',
  'Married-spouse-absent',
  'Transport-moving',
  'Other',
  'Male',
  '20',
  'El-Salvador',
  '<=50K'],
 ['19',
  'Private',
  'Some-college',
  'Never-married',
  'Transport-moving',
  'White',
  'Male',
  '40',
  'United-States',
  '<=50K'],
 ['47',
  'Private',
  '11th',
  'Divorced',
  'Other-service',
  'White',
  'Female',
  '15',
  'United-States',
  '<=50K'],
 ['30',
  'Local-gov',
  'HS-grad',
  'Married-civ-spouse',
  'Protective-serv',
  'White',
  'Male',
  '40',
  'United-States',
  '>50K'],
 ['37',
  'Private',
  'Bachelors',
  'Separated',
  'Other-service',
  'White',
  'Male',
  '70',
  'England',
  '<=50K'],
 ['35',
  'Private',
  'HS-grad',
  'Married-civ-spouse',
  'Adm-clerical',
  'White',
  'Male',
  '40',
  'United-States',
  '<=50K'],
 ['33',
  'Private',
  'HS-grad',
  'Married-civ-sp

## Question 1

These values make sence for yearly salaries in the 90s. According to google, median salary in the 90s was around 20,000 dollars so 25\% of people around \$50,000 makes sence

In [4]:
#!cat income.train.txt.5k | sort -nk1 | head -1

train_pos,dev_pos = 0,0
train_tot, dev_tot = 0,0

for row in train:
    train_tot += 1
    if(row[-1]) == '>50K':
        train_pos += 1
        
print('Train Positive Percent is:', train_pos, 'of', train_tot, 'or', train_pos/train_tot)
        
        
for row in dev:
    dev_tot += 1
    if(row[-1]) == '>50K':
        dev_pos += 1

print('Dev Positive Percent is:', dev_pos, 'of', dev_tot, 'or', dev_pos/dev_tot)


 

Train Positive Percent is: 1251 of 5000 or 0.2502
Dev Positive Percent is: 236 of 1000 or 0.236


## Question 2

Q: What are the youngest and oldest ages in the training set? What are the least and most amounts of hours per week do people in this set work? Hint: cat income.train.txt.5k | sort -nk1 | head -1 

In [5]:
min_age = 100
max_age = 0
min_hours = 100
max_hours = 0


for row in train:
    if int(row[0]) < min_age:
        min_age = int(row[0])
    if int(row[0]) > max_age:
        max_age = int(row[0])
    if int(row[-3]) < min_hours:
        min_hours = int(row[-3])
    if int(row[-3]) > max_hours:
        max_hours = int(row[-3])
        
        
print('Min Hours', min_hours, 'min age', min_age)
print('Max Hours', max_hours, 'max age', max_age)

Min Hours 1 min age 17
Max Hours 99 max age 90


## Question 6

Q: How many features do you have in total (i.e., the dimensionality)? 

In [65]:
# How many features do you have in total?
mapping = {}
new_data = []

#BINARIZE DEV
for row in dev:
    new_row = []
    cleanRow = row[1:7] + row[8:9] 
    for j, x in enumerate(cleanRow):
        feature = (j, x)
        if feature not in mapping:
            mapping[feature] = len(mapping) # insert a new feature into the index
        new_row.append(mapping[feature])
    new_data.append(new_row)
    
bindata_dev = np.zeros((1000,len(mapping)))
bindata_dev
for i, row in enumerate(new_data):
    for x in row:
        bindata_dev[i][x] = 1
        
bindata_dev = np.zeros((1000,92))

for i, row in enumerate(new_data):
    for x in row:
        bindata_dev[i][x] = 1

        
new_data_train = []

#BINARIZE TRAIN
for row_train in train:
    new_row_train = []
    cleanRow_train = row_train[1:7] + row_train[8:9] 
    for j_train, x_train in enumerate(cleanRow_train):
        feature_train = (j_train,x_train)
        if feature_train not in mapping:
            mapping[feature_train] = len(mapping)
        new_row_train.append(mapping[feature_train])
    new_data_train.append(new_row_train)
    
bindata_train = np.zeros((5000,92))

for i, row_t in enumerate(new_data_train):
    for x_t in row_t:
        bindata_train[i][x_t] = 1


In [8]:
len(new_data)

1000

In [66]:
#shape = np.shape(new_data)
#+ row[8:]

#for row in dev:
#    print(row)
bindata_train[0:3]

#row_train[1:7] + row_train[8:9] 
#len(new_data_train)
#cleanRow
#new_data_train
#np.shape(bindata_train)

#bindata_dev[0:3]

array([[0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.

# PART TWO

## Question 1
Q: Find the five (5) people closest to the last person (in Euclidean distance) in dev, and report their distances:

In [93]:
from math import sqrt

euclid_list = []
manhat_list = []

personIndex = -1

lastPerson = bindata_train[personIndex]

print(lastPerson)
#euclid_Dist = np.linalg.norm((bindata_train - lastPerson), axis = 1)    

for i,row in enumerate(bindata_train):
    euclid_list.append(np.sqrt(sum((row - lastPerson)**2)) + ((int(train[i][0]) - int(train[personIndex][0]))/50)**2 + ((int(train[i][7]) - int(train[personIndex][7]))/50)**2)
    manhat_list.append(sum(abs(row - lastPerson) + abs((int(train[i][0]) - int(train[personIndex][0]))/50) + abs((int(train[i][7]) - int(train[personIndex][7]))/50)))
    
min_euclid = np.argpartition(euclid_list,5)[:5]
min_manhat = np.argpartition(manhat_list,5)[:5]


print('Original Person: \n', dev[personIndex])
for i,index in enumerate(min_euclid):    
    print("\nIndex:", index, "e-distance:", euclid_list[index], "\nperson:", train[index])
                       
for i in min_euclid:    
    print("\nIndex:", i, "manhat-distance:", manhat_list[i], "\nperson:", train[i])
                       

[0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Original Person: 
 ['58', 'Private', 'HS-grad', 'Widowed', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 4999 e-distance: 0.0 
person: ['21', 'Private', 'Assoc-voc', 'Never-married', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 934 e-distance: 0.0004 
person: ['20', 'Private', 'Assoc-voc', 'Never-married', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 1221 e-distance: 0.010000000000000002 
person: ['26', 'Private', 'Assoc-voc', 'Never-married', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 3084 e-distance: 0.020000000000000004 
person: ['26', 'Private', 'Assoc-voc', 'Never-married', 'Adm-clerica

In [90]:
euclid_list

[3.790277660168379,
 2.9440271247461904,
 3.5718776601683797,
 3.1818776601683796,
 2.5518897427831777,
 3.7062776601683796,
 3.556677660168379,
 2.08,
 3.0048271247461904,
 3.9046776601683795,
 3.7740573867739413,
 1.4558135623730952,
 2.9168271247461903,
 3.5417016151377543,
 2.8448271247461903,
 2.497889742783178,
 2.9840271247461905,
 3.03202712474619,
 3.542501615137754,
 3.0220271247461903,
 3.0270897427831778,
 3.6522776601683793,
 2.4510897427831777,
 3.5980271247461904,
 3.1420271247461904,
 2.88762712474619,
 2.8352271247461904,
 3.0588271247461902,
 2.8608271247461903,
 3.7145016151377543,
 3.12002712474619,
 2.449489742783178,
 2.0915999999999997,
 3.4538776601683794,
 2.8720271247461904,
 3.5718776601683797,
 2.465889742783178,
 3.982501615137754,
 3.2396271247461903,
 2.6610897427831777,
 2.9884271247461904,
 2.0292,
 2.8348271247461905,
 3.2588271247461904,
 3.588677660168379,
 3.5926776601683796,
 3.0220271247461903,
 3.4122776601683795,
 2.90682712474619,
 2.6350897427

## Question 2
Q: Redo the above using Manhattan distance.

In [86]:
for i in min_manhat:    
    print("\nIndex:", i, "manhat-distance:", manhat_list[i], "\nperson:", train[i])                     
        


Index: 3399 manhat-distance: 11.679999999999954 
person: ['50', 'Private', 'HS-grad', 'Never-married', 'Tech-support', 'White', 'Male', '15', 'United-States', '<=50K']

Index: 746 manhat-distance: 18.72000000000001 
person: ['51', 'Self-emp-not-inc', '9th', 'Married-civ-spouse', 'Craft-repair', 'White', 'Male', '20', 'United-States', '<=50K']

Index: 0 manhat-distance: 0.0 
person: ['50', 'Self-emp-not-inc', 'Bachelors', 'Married-civ-spouse', 'Exec-managerial', 'White', 'Male', '13', 'United-States', '<=50K']

Index: 3341 manhat-distance: 18.72000000000001 
person: ['51', 'Self-emp-not-inc', 'Some-college', 'Married-civ-spouse', 'Craft-repair', 'White', 'Male', '20', 'United-States', '<=50K']

Index: 4518 manhat-distance: 18.720000000000013 
person: ['51', 'Private', 'Bachelors', 'Married-civ-spouse', 'Craft-repair', 'White', 'Male', '20', 'United-States', '>50K']


## Question 3
Q: What are the 5-NN predictions for this person (Euclidean and Manhattan)? Are these predictions correct?

*Euclidean*  
The nearest neighbors suggest that this person should be:
21, Private, HS-grad, Never-married, ??(tie), white, Male, ~41.5, united states, and <=50k. 

This is accurate on industry, education, race, hours worked, and country. The salary prediction is not correct.

*Manhattan*  
The nearest neighbors suggest that this person should be:

21, Private, HS-grad, never-married, adm-clerical, white, male, 40, usa, <=50k

This is only accurate on industry, education, job,race, hours worked,and country. The salary prediction is not correct.



## Question 4
Q: Redo all the above using 9-NN (i.e., find top-9 people closest to this person first).

In [69]:
min_euclid = np.argpartition(euclid_list,9)[:9]
min_manhat = np.argpartition(manhat_list,9)[:9]


print('Original Person: \n', dev[-1])
for i in min_euclid:    
    print("\nIndex:", i, "e-distance:", round(euclid_list[i], 3), "\nperson:", train[i])
                       
        
for i in min_manhat:    
    print("\nIndex:", i, "manhat-distance:", round(manhat_list[i],3), "\nperson:", train[i])                     
        


Original Person: 
 ['58', 'Private', 'HS-grad', 'Widowed', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 31 e-distance: 2.646 
person: ['21', 'Private', 'Some-college', 'Never-married', 'Machine-op-inspct', 'White', 'Male', '40', 'United-States', '<=50K']

Index: 533 e-distance: 2.646 
person: ['21', 'Private', 'Some-college', 'Never-married', 'Handlers-cleaners', 'White', 'Male', '40', 'United-States', '<=50K']

Index: 1530 e-distance: 2.646 
person: ['21', 'Private', 'HS-grad', 'Married-civ-spouse', 'Handlers-cleaners', 'White', 'Male', '40', 'United-States', '<=50K']

Index: 4999 e-distance: 2.646 
person: ['21', 'Private', 'Assoc-voc', 'Never-married', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 999 e-distance: 2.567 
person: ['38', 'Private', 'Bachelors', 'Married-civ-spouse', 'Sales', 'White', 'Male', '42', 'United-States', '>50K']

Index: 3772 e-distance: 2.646 
person: ['21', 'Private', 'HS-grad', 'Never-married', 'Adm

*Euclidean*  
The nearest neighbors suggest that this person should be:
21, Private, HS-grad, Never-married, ??(tie), white, Male, ~40.5, united states, and <=50k. 

This is accurate on industry, education, race, hours worked, and country. The salary prediction is not correct.

*Manhattan*  
The nearest neighbors suggest that this person should be:

21, Private, HS-grad, never-married, adm-clerical, white, male, 40, usa, <=50k

This is only accurate on industry, education, job,race, hours worked,and country. The salary prediction is not correct.



# PART THREE

### K NEAREST NEIGHBOR CLASSIFICATION

#### 1. Implement the basic k-NN classifier (with the default Euclidean distance)
Q: Is there any work in training after finishing the feature map?  ?????  

    No, we are not trainging in this example


Q: What’s the time complexity of k-NN to test one example (dimensionality d, size of training set |D|)?  
    
    1. Calculating the distance between each person: O(D) * d (all people)
    2. Sort the algorithm: O(D^2)
    3. Time to check the top matches: k
    4. Overall time complexity: O(D) * d + D^2 + k
    


Q: Do you really need to sort the distances first and then choose the top k? Hint: there is a faster way to choose top k without sorting

    I belive it would be faster to search the list of distances for minimum and remove them without replacement. This time complexity would simply be D*k.


In [64]:
def calc_knn(k, index, dataset = 'dev', p = 'yes'):
    euclid_list = []
    lastPerson = bindata_dev[index]
    dist = []
    
    if dataset == 'dev':
        print('dev')
        for i,row in enumerate(bindata_dev):
            euclid_list.append(np.sqrt(sum((row - lastPerson)**2)) + ((int(train[i][0]) - int(train[personIndex][0]))/50)**2 + ((int(train[i][7]) - int(train[personIndex][7]))/50)**2)
    
    else:
        #for i,row in enumerate(bindata_train):
        dist.append(np.linalg.norm(bindata_train - lastPerson, axis = 1))
            #euclid_list.append(np.sqrt(sum((row - lastPerson)**2)) + ((int(train[i][0]) - int(train[personIndex][0]))/50)**2 + ((int(train[i][7]) - int(train[personIndex][7]))/50)**2)
 
    
    min_euclid = np.argpartition(dist[0],k)[:k]  # np.argsort(dist[0])[:k]
    #sorted_index = np.argsort(min_euclid)[:k]
    #sorted_topk = sorted_index[:k]
    
    if p == 'yes':
        #print('euclid_list', euclid_list)
        #print('topk', sorted_index)
        print('Original Person: \n', dev[-1])
        #print('dist0', dist[0])
        for i in range(k):    
            print("\nIndex:", min_euclid[i], "e-distance:", dist[0][min_euclid[i]], "\nperson:", train[min_euclid[i]])
    print(min_euclid)
    print(dist[0][3779])
    print(dist[0][517])
    print(dist[0][3031])
    print(dist[0][3895])
    print(dist[0])
    #return sorted_topk
        
k = 5 
#min_euclid = calc_knn(k, -1)
print('\ntrain\n')
#min_euclid_train = calc_knn(k, -1,'train')

min_euclid_train = calc_knn(k, 1,'train')


train

Original Person: 
 ['58', 'Private', 'HS-grad', 'Widowed', 'Adm-clerical', 'White', 'Female', '40', 'United-States', '<=50K']

Index: 3779 e-distance: 2.449489742783178 
person: ['57', 'Private', '5th-6th', 'Divorced', 'Transport-moving', 'White', 'Male', '40', 'United-States', '<=50K']

Index: 517 e-distance: 2.449489742783178 
person: ['47', 'Private', '9th', 'Married-spouse-absent', 'Handlers-cleaners', 'White', 'Male', '40', 'El-Salvador', '<=50K']

Index: 3031 e-distance: 2.449489742783178 
person: ['45', 'Private', '5th-6th', 'Married-civ-spouse', 'Transport-moving', 'White', 'Male', '38', 'Mexico', '<=50K']

Index: 3895 e-distance: 2.449489742783178 
person: ['31', 'Private', 'Some-college', 'Married-civ-spouse', 'Transport-moving', 'White', 'Male', '45', 'El-Salvador', '<=50K']

Index: 2324 e-distance: 2.449489742783178 
person: ['50', 'Private', '5th-6th', 'Married-civ-spouse', 'Transport-moving', 'White', 'Male', '37', 'Mexico', '<=50K']
[3779  517 3031 3895 2324]
2.4

In [36]:
dist[0]

NameError: name 'dist' is not defined

dimensionality:  80
80
[[71 79 78 75 29 59 73 56 22 66 60 62 77 76 54 67 72 58 61 70 53 69 68 57
  52 64 42 74 55 17 65 44  8 47 12 15 24 21 18 20 33 63 28 13 45 41  1 37
  27 19 10  6 36  4 16 14 31  3 40 51 46 32 30 35 34 38 26 43  9  0 49 48
  25 11 23 50  2  7 39  5]
 [71 79 75 78 59 29 73 22 56 66 60 62 77 76 54 72 67 58 61 70 68 69 53 57
  52 42 64 74 17 55 65 44  8 47 12 15 24 21 18 33 20 63 28 13 45 41  1 37
  27 19 10  6  4 16 14 31  3 40  5 51 46 32 30 35 34 39 38 50 43  7  0  9
   2 49 48 25 23 11 26 36]]
k=1    train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.2%)
k=3    train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=5    train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=7    train_err 25.1% (+:  0.1%) dev_err 23.5% (+:  0.3%)
k=9    train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=99   train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=999  train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=9999 train_err 25.0% (+:  0.0%) dev_err 23.6% (+:  0.0%)
k=1000

### Error rate calculation

In [18]:
# CODE FROM SLACK TA
## ARE WE COMPARING THE LAST PERSON IN DEV? OR WHO??

# one prediction for each row in dev

correct = 0
k = 5

for i,entry in enumerate(dev): # enumerate each person in the dev set
    num_positives = 0
    min_euclid_train = calc_knn(k, i,'train', p = 'false')
    
    # iterate over top people in training set
    for person_idx in min_euclid_train: 
        #print(train[person_idx][-1])
        
        if train[person_idx][-1] == ">50K":
            
            #print(1, train[person_idx])
            num_positives +=1
    if num_positives > k/2:
        predicted_label = ">50K"
    else:
         predicted_label = "<=50K"
    
    #print(predicted_label , dev[-1][-1])
    
    if predicted_label.lower() == dev[-1][-1].lower():
        #print('match')
        correct += 1
        
    if i in range(1,1000,100):
        print(i)
print(correct)


1
101
201
301
401
501
601
701
801
901
1000


In [19]:
#for i in min_euclid_train:
#    print(i)
min_euclid_train



array([3772,  999, 4931, 3855,   31], dtype=int64)

In [33]:
Income predicted will contain predicted label at the end of each row

[ 999    0 3338 3337 3336]
