In [2]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
x = np.array([1,2,3])

In [4]:
x.shape

(3,)

In [5]:
x

array([1, 2, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
np.array([[1,2], [4,5]])

array([[1, 2],
       [4, 5]])

In [8]:
A = np.array([[1,2], [4,5]])

In [9]:
A.shape

(2, 2)

In [10]:
type(A)

numpy.ndarray

In [11]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = np.arange(10)

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = range(10)

In [16]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
y + y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
x + x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
y * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
y + y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.concatenate((x,x))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linalg.norm(x)

16.881943016134134

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
[a*a for a in x]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [26]:
sum([a*a for a in x])

285

In [27]:
sqrt(sum([a*a for a in x]))

NameError: name 'sqrt' is not defined

In [28]:
from math import *

In [29]:
sqrt(sum([a*a for a in x]))

16.881943016134134

In [30]:
np.linalg.norm(np.array([1,2]))

2.2360679774997898

In [31]:
sqrt(1*1+2*2)

2.23606797749979

In [32]:
a = np.array([1,2])

In [33]:
b = np.array([3,1])

In [34]:
a + b

array([4, 3])

In [35]:
a * b

array([3, 2])

In [36]:
a.dot(b)

5

In [37]:
sum(x*y for (x,y) in zip(a,b))

5

In [38]:
zip(a,b)

[(1, 3), (2, 1)]

In [41]:
sum([x*y for (x,y) in zip(a,b)])

5

In [45]:
import matplotlib.pyplot as plt

In [46]:
plt.plot([1,2])

In [3]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [48]:
plot([1,2,4])

In [49]:
plot([10,15,16],[1,2,4])

In [50]:
np.random.rand()

0.8583903214765335

In [51]:
np.random.rand()

0.7765422305628009

In [52]:
np.random.rand(2)

array([ 0.23372757,  0.20115827])

In [53]:
np.random.rand(10,2)

array([[ 0.66173485,  0.61348838],
       [ 0.67514394,  0.83686444],
       [ 0.72159929,  0.4914619 ],
       [ 0.17796346,  0.97655882],
       [ 0.03882643,  0.82042706],
       [ 0.59739194,  0.72429001],
       [ 0.42287466,  0.12304079],
       [ 0.45258519,  0.11975368],
       [ 0.12152163,  0.48147918],
       [ 0.37357522,  0.86923485]])

In [4]:
X = np.random.rand(10,2)

In [55]:
X

array([[ 0.49778099,  0.99916324],
       [ 0.50111003,  0.79123508],
       [ 0.44058869,  0.41190524],
       [ 0.17639237,  0.79767185],
       [ 0.97237422,  0.52793962],
       [ 0.31779727,  0.55978925],
       [ 0.48396518,  0.30106021],
       [ 0.53884929,  0.49992757],
       [ 0.46498784,  0.95715905],
       [ 0.27918222,  0.95762105]])

In [56]:
X[0]

array([ 0.49778099,  0.99916324])

In [57]:
X[-1]

array([ 0.27918222,  0.95762105])

In [58]:
X[:,0]

array([ 0.49778099,  0.50111003,  0.44058869,  0.17639237,  0.97237422,
        0.31779727,  0.48396518,  0.53884929,  0.46498784,  0.27918222])

In [59]:
X[:,1]

array([ 0.99916324,  0.79123508,  0.41190524,  0.79767185,  0.52793962,
        0.55978925,  0.30106021,  0.49992757,  0.95715905,  0.95762105])

In [60]:
plot(X)

In [6]:
plot(X[:,0], X[:,1], 'w')

In [62]:
clf()

In [7]:
plot(X[:,0], X[:,1], 'sb')

In [64]:
clf()

In [65]:
plot(X[:,0], X[:,1], 'dr')

In [8]:
x = np.arange(10)

In [67]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.random.rand(10)

array([ 0.97480597,  0.64008069,  0.65382282,  0.29631071,  0.42093465,
        0.83443238,  0.81486536,  0.11777681,  0.98008608,  0.03348082])

In [69]:
x + np.random.rand(10)

array([ 0.28442056,  1.72609062,  2.78666341,  3.84049696,  4.41822019,
        5.65230902,  6.48434679,  7.37458957,  8.02579708,  9.22969233])

In [70]:
x = np.arange(10) + np.random.rand(10)

In [71]:
x

array([ 0.28455454,  1.92332769,  2.5219964 ,  3.21559561,  4.56231848,
        5.87271772,  6.71088948,  7.49770254,  8.67680144,  9.44851509])

In [72]:
clf()

In [73]:
plot(x, '+c')

In [74]:
plot([0,10], [0,10])

In [75]:
clf()

In [76]:
np.arange(3)

array([0, 1, 2])

In [77]:
np.arange(3) - 1

array([-1,  0,  1])

In [78]:
np.arange(3) - np.array([1,1,1])

array([-1,  0,  1])

In [79]:
np.random.rand(10)

array([ 0.50280047,  0.8728428 ,  0.6712622 ,  0.53834089,  0.29592611,
        0.04483383,  0.18413799,  0.07692249,  0.2559796 ,  0.69887885])

In [80]:
np.random.rand(10) - 0.5

array([ 0.17127389, -0.2856479 ,  0.28903794, -0.12379614,  0.19773461,
        0.23297174,  0.18708496, -0.26494435, -0.08530763,  0.2888253 ])

In [81]:
x = np.arange(10) + np.random.rand(10) - 0.5

In [82]:
plot(x, '+b')

In [83]:
plot([0,10],[0,10])

In [1]:
x = np.arange(10)

NameError: name 'np' is not defined

In [85]:
y = [x_i + np.random.rand() for x_i in x]

In [86]:
y

[0.49495809494707976,
 1.9758107580649134,
 2.4092093774986578,
 3.3829355494929874,
 4.621688348491924,
 5.4428884413352545,
 6.2438798209234116,
 7.9134930606787037,
 8.5494739847293992,
 9.9474800918610491]

In [87]:
y = np.array([x_i + np.random.rand() for x_i in x])

In [88]:
y

array([ 0.03436254,  1.70338587,  2.57420221,  3.0218875 ,  4.90091402,
        5.85828911,  6.09086192,  7.76160075,  8.45925694,  9.61661804])

In [89]:
y = x + np.random.rand(10) - 0.5

In [90]:
y

array([ 0.2808971 ,  1.40123739,  1.51156306,  2.56079105,  4.04751994,
        4.72936123,  6.11047533,  6.64589139,  8.24480994,  9.16149616])

In [91]:
plot(x,y, 'or')

In [92]:
clf()

In [93]:
x = np.arange(0,10,0.1)

In [94]:
x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [95]:
y = x + np.random.rand(100) - 0.5

In [96]:
y

array([ -0.22727657,   0.07099117,   0.3713678 ,  -0.13535819,
         0.32256028,   0.23990975,   0.1052552 ,   0.69754625,
         0.7671883 ,   0.5361508 ,   0.70676845,   1.41904196,
         0.8946635 ,   0.9723323 ,   0.96713235,   1.64780343,
         1.42529496,   1.36150121,   2.2719586 ,   2.23529469,
         1.95053916,   1.8063274 ,   2.24361423,   2.45319016,
         2.5679756 ,   2.01476063,   2.50631212,   2.64786922,
         2.56070147,   3.35204677,   3.11772556,   3.5778462 ,
         3.51653925,   3.53452623,   3.01880009,   3.0084276 ,
         3.5940909 ,   3.60576388,   3.54369403,   3.44467147,
         4.1379646 ,   4.29893037,   4.03550402,   4.28035885,
         4.81748697,   4.22370131,   4.51587319,   4.4342147 ,
         5.09064898,   5.12038234,   5.28446778,   4.82757369,
         5.4992088 ,   5.58607387,   5.2497665 ,   5.79802257,
         5.59146746,   5.84932188,   6.23920284,   5.49117129,
         5.68184887,   5.88550365,   6.27809116,   6.27

In [97]:
plot(x,y, 'sg')

In [98]:
clf()

In [99]:
plot(x,y, '+g')

In [100]:
a, b = np.polyfit(x,y,1)

In [101]:
a, b

(1.015783710606174, -0.094700002780409798)

In [102]:
plot(x, a*x+b, '-c')

In [103]:
clf()

In [104]:
x = np.arange(0,10,0.5)

In [105]:
y = x + np.random.randn(20) - 0.5

In [106]:
plot(x, y, '+b')

In [107]:
a, b = np.polyfit(x,y,1)

In [108]:
a,b

(1.1213652693102711, -0.91761099908200705)

In [109]:
plot(x, a*x+b, '-r')

In [110]:
a, b, c = np.polyfit(x,y,2)

In [111]:
a,b,c

(0.0041806166134694261, 1.0816494114823116, -0.85803721234006824)

In [112]:
plot(x, a*x*x+b*x+c, '-c')

In [113]:
a, b, c, d = np.polyfit(x,y,3)

In [114]:
plot(x, a*x*x*x+b*x*x+c*x+d, '-g')

In [115]:
plot(x, a*x*x*x+b*x*x+c*x+d, '-w')

In [116]:
xx = np.arange(0,10,0.01)

In [117]:
plot(xx, a*xx*xx*xx+b*xx*xx+c*xx+d, '-g')

In [118]:
a, b, c, d, e = np.polyfit(x,y,4)

In [119]:
plot(xx, a*xx*xx*xx*xx+b*xx*xx*xx+c*xx*xx+d*xx+e, '-b')

In [120]:
clf()

In [121]:
axes().set_aspect('equal')

In [122]:
axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [123]:
show()

In [124]:
grid()

In [125]:
xticks(np.arange(-10,10,1))

([<matplotlib.axis.XTick at 0x118fbeb50>,
 <a list of 20 Text xticklabel objects>)

In [126]:
yticks(np.arange(-10,10,1))

([<matplotlib.axis.YTick at 0x10600ded0>,
 <a list of 20 Text yticklabel objects>)

In [127]:
a = np.array([4,2])

In [128]:
plot((0,a[0]), (0,a[1]))

In [129]:
plot((0,a[0]), (0,a[1]), 'w')

In [130]:
quiver(0,0,a[0],a[1])

In [131]:
quiver(0,0,a[0],a[1], angles='xy', scale_units='xy', scale=1, color='c')

In [133]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [135]:
xticks(np.arange(-10,10,1))

([<matplotlib.axis.XTick at 0x11319bd90>,
 <a list of 20 Text xticklabel objects>)

In [136]:
yticks(np.arange(-10,10,1))

([<matplotlib.axis.YTick at 0x11321e350>,
 <a list of 20 Text yticklabel objects>)

In [137]:
grid()

In [138]:
quiver(0,0,a[0],a[1], angles='xy', scale_units='xy', scale=1, color='b')

In [139]:
b = np.array([1,3])

In [140]:
quiver(0,0,b[0],b[1], angles='xy', scale_units='xy', scale=1, color='r')

In [143]:
def arrow((x,y), (x1,y1), color='b'):
    quiver(x,y, x1, y1, angles='xy', scale_units='xy', scale=1, color=color)

In [144]:
arrow((0,0), (-2,2))

In [145]:
arrow((0,0), (2,-5))

In [146]:
arrow((0,0), np.array([1,-1]))

In [147]:
arrow((0,0), (-2,2), 'w')

In [148]:
arrow((0,0), (2,-5), 'w')

In [149]:
arrow((0,0), np.array([1,-1]), 'w')

In [150]:
a + b

array([5, 5])

In [151]:
arrow(a, b, 'r')

In [152]:
arrow((0,0), a+b, 'c')

In [153]:
a - b

array([ 3, -1])

In [154]:
arrow(b, a, 'g')

In [155]:
arrow(b, a-b, 'black')

In [156]:
arrow((0,0), a-b, 'black')

In [157]:
np.linalg.norm(a)

4.4721359549995796

In [158]:
np.linalg.norm(b)

3.1622776601683795

In [159]:
a * b

array([4, 6])

In [160]:
a.dot(b)

10

In [161]:
a,b

(array([4, 2]), array([1, 3]))

In [162]:
norm = lambda x : np.linalg.norm(x)

In [163]:
norm(a)

4.4721359549995796

In [164]:
a.dot(b) / (norm(a) * norm(b))

0.70710678118654746

In [165]:
theta = arccos(0.70710678118654746)

In [166]:
theta

0.78539816339744839

In [167]:
theta / np.pi * 180

45.000000000000007

In [168]:
b.dot(a-b)

0

In [169]:
costheta = a.dot(b) / (norm(a) * norm(b))

In [170]:
costheta

0.70710678118654746

In [171]:
norm(b) * costheta

2.2360679774997898

In [172]:
a / norm(a) * norm(b) * costheta

array([ 2.,  1.])

In [173]:
c = a / norm(a) * norm(b) * costheta

In [174]:
arrow((0,0), c, 'orange')

In [175]:
#c = a/|a| * (a.b)/|a| = a (a.b) /|a|^2 

In [176]:
d = a * a.dot(b) / norm(a)**2

In [177]:
d

array([ 2.,  1.])

In [178]:
d == c

array([False, False], dtype=bool)

In [179]:
c

array([ 2.,  1.])

In [180]:
arrow((0,0), d, 'magenta')

In [181]:
clf()

In [182]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [183]:
X = np.random.randn(10,2)

In [184]:
X

array([[ 1.39689794, -0.48565161],
       [ 0.89730497,  0.90118446],
       [ 1.56949705, -0.15333455],
       [ 0.80697782,  0.29596034],
       [-0.32756589, -0.96413274],
       [ 0.27009722, -0.12474436],
       [-0.76212338, -0.66759742],
       [ 1.24014011,  0.96403346],
       [-0.0519767 , -1.11914678],
       [-1.14477151, -0.38563083]])

In [185]:
plot(X)

In [186]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [187]:
plot(X[:,0], X[:,1], '+b')

In [188]:
np.random.rand(10,2)

array([[ 0.12491728,  0.6719976 ],
       [ 0.12604374,  0.94512288],
       [ 0.41796118,  0.72220964],
       [ 0.88262918,  0.23090028],
       [ 0.83165674,  0.42108933],
       [ 0.36628563,  0.1905579 ],
       [ 0.96681112,  0.98246465],
       [ 0.69677657,  0.92529013],
       [ 0.82449313,  0.73476266],
       [ 0.65935073,  0.45264243]])

In [189]:
Y = np.random.rand(10,2)

In [190]:
plot(Y[:,0], Y[:,1], '.r')

In [191]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [192]:
X = np.random.randn(50,2)

In [195]:
def myplot(X, opts=""):
    plot(X[:,0], X[:,1], opts)

In [196]:
myplot(X)

In [197]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [198]:
def myplot(X, opts="."):
    plot(X[:,0], X[:,1], opts)

In [199]:
myplot(X)

In [200]:
def myplot(X, opts=".b"):
    x, y = X.T
    plot(x, y, opts)

In [201]:
myplot(X)

In [202]:
X

array([[ 0.18841264, -1.83245892],
       [-0.06828302, -0.65347585],
       [ 1.17620834,  0.41352522],
       [ 0.78222377,  0.45667559],
       [ 1.29747983,  0.92106285],
       [-0.19479863,  1.18388679],
       [-0.09366568,  0.38390232],
       [-2.10509228,  0.08479513],
       [-0.3365187 , -1.19701218],
       [ 0.62671504,  0.62120673],
       [ 0.4289131 ,  1.79909917],
       [ 0.67279892, -0.09742841],
       [-0.57307848, -0.07627243],
       [-0.66945148, -0.3052148 ],
       [ 2.27913691,  0.61492526],
       [-0.34809856, -0.22647503],
       [ 0.96108136, -0.30135971],
       [ 0.41103856, -0.43138698],
       [ 0.77931948,  0.65973648],
       [ 3.22357636, -0.66812822],
       [ 1.07895742,  0.84848122],
       [ 2.52056042, -0.73723895],
       [-1.94124149,  1.13834404],
       [-0.05614673, -0.68359579],
       [-0.11812002, -0.68222464],
       [-0.66070355,  0.43476077],
       [ 0.30208623, -0.22129952],
       [ 0.17354976, -2.44565873],
       [ 0.2137391 ,

In [203]:
X.T

array([[ 0.18841264, -0.06828302,  1.17620834,  0.78222377,  1.29747983,
        -0.19479863, -0.09366568, -2.10509228, -0.3365187 ,  0.62671504,
         0.4289131 ,  0.67279892, -0.57307848, -0.66945148,  2.27913691,
        -0.34809856,  0.96108136,  0.41103856,  0.77931948,  3.22357636,
         1.07895742,  2.52056042, -1.94124149, -0.05614673, -0.11812002,
        -0.66070355,  0.30208623,  0.17354976,  0.2137391 , -1.31849309,
        -1.73624918, -0.50469089,  1.24441495, -0.80650605, -0.76742007,
        -1.89957642, -1.6468677 ,  0.34908032,  1.18568221,  0.70713294,
        -1.71932226,  1.13593056,  1.22006054,  1.04063387, -1.70654753,
        -0.44836899, -0.76417066, -0.02719093, -0.79705992,  0.49287219],
       [-1.83245892, -0.65347585,  0.41352522,  0.45667559,  0.92106285,
         1.18388679,  0.38390232,  0.08479513, -1.19701218,  0.62120673,
         1.79909917, -0.09742841, -0.07627243, -0.3052148 ,  0.61492526,
        -0.22647503, -0.30135971, -0.43138698,  0.

In [204]:
a = np.random.randn(5,2)

In [205]:
a

array([[ 0.0484303 , -0.24615505],
       [-0.88082047, -0.90812359],
       [-1.45403503,  0.44370809],
       [ 0.39714658, -0.94192874],
       [-1.05795811,  0.7972823 ]])

In [206]:
a.T

array([[ 0.0484303 , -0.88082047, -1.45403503,  0.39714658, -1.05795811],
       [-0.24615505, -0.90812359,  0.44370809, -0.94192874,  0.7972823 ]])

In [207]:
x,y = a.T

In [208]:
x

array([ 0.0484303 , -0.88082047, -1.45403503,  0.39714658, -1.05795811])

In [209]:
y

array([-0.24615505, -0.90812359,  0.44370809, -0.94192874,  0.7972823 ])

In [210]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [211]:
myplot(X*10)

In [212]:
myplot(X*5)

In [213]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [214]:
myplot(X*5)

In [215]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [216]:
myplot(X*2)

In [217]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [218]:
myplot(np.random.randn(1000,2)*2)

In [219]:
clf(); axes().set_aspect('equal'); axis([-10,10,-10,10])

[-10, 10, -10, 10]

In [220]:
X = np.random.randn(1000,2)*5; myplot(X)

In [221]:
w = np.array([1,1])

In [222]:
arrow((0,0),w, 'r')

In [223]:
X

array([[ 1.07417723, -4.71410298],
       [-5.21825501,  4.37419835],
       [-3.63562451,  3.70788115],
       ..., 
       [-5.49917844,  3.72759038],
       [-0.56394384, -1.58211965],
       [ 1.44803264,  4.22161979]])

In [224]:
X.dot(w)

array([ -3.63992574e+00,  -8.44056658e-01,   7.22566408e-02,
        -7.87192338e+00,  -7.51800310e+00,   1.35768399e+00,
        -1.33784009e+00,  -7.22808805e+00,   1.74774284e+00,
         1.53066215e+01,   3.94288602e+00,   4.82772760e+00,
         2.62795227e+00,   7.25264849e+00,   9.73993780e+00,
        -1.00493003e+01,  -1.00783748e+00,   7.70626656e+00,
         1.41084770e+01,   1.79130304e+00,   9.24906724e+00,
         1.16112599e+01,   1.19679841e+01,   3.53902690e+00,
        -3.95158251e+00,  -1.23057482e+01,   6.40794182e+00,
         1.02753789e+01,   1.98501249e+00,   9.39292611e-01,
        -8.30016071e-01,  -4.49167194e+00,   2.94446375e+00,
         1.68151714e+00,   3.46344941e+00,   6.08161322e-01,
        -1.89224638e+00,   2.59292749e+00,   5.32580735e+00,
        -1.60419312e+00,   4.03498473e+00,   4.06426736e-01,
        -6.46533584e+00,   5.42519639e-01,  -1.07550140e+01,
        -1.91101629e+00,   1.15798929e+01,  -8.36379163e+00,
         5.25852563e+00,

In [225]:
X[0].dot(w)

-3.6399257432223591

In [226]:
X[-1].dot(w)

5.6696524239073423

In [227]:
pos = np.array([x for x in X if x.dot(w) > 0])

In [228]:
len(pos)

525

In [229]:
pos = X [X.dot(w) > 0]

In [230]:
len(pos)

525

In [231]:
myplot(pos, '.r')

In [232]:
X.dot(w) > 0

array([False, False,  True, False, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True, False,  True, False,
       False,  True, False,  True, False,  True,  True, False,  True,
       False,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True, False, False, False, False,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False,  True,  True,  True, False, False, False, False,  True,
       False, False,

In [233]:
neg = X [X.dot(w) < 0]

In [234]:
len(neg)

475

In [235]:
myplot(neg, '.c')

In [236]:
bad = X[abs(X.dot(w)) < 1]

In [237]:
len(bad)

115

In [238]:
myplot(bad, '.w')

In [239]:
bad = X[abs(X.dot(w)) < 5]

In [240]:
myplot(bad, '.w')

In [241]:
w

array([1, 1])

In [242]:
w /= norm(w)

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
  """Entry point for launching an IPython kernel.


In [243]:
w

array([0, 0])

In [244]:
w = array([1,1], dtype=float)

In [245]:
w /= norm(w)

In [246]:
w

array([ 0.70710678,  0.70710678])

In [247]:
bad = X[abs(X.dot(w)) < 10]

In [248]:
myplot(bad, '.w')

In [249]:
myplot(X, '.b')

In [250]:
bad = X[(-2 < X.dot(w)) & (X.dot(w) < 1) ]

In [251]:
len(bad)

219

In [252]:
myplot(bad, '.w')